### PR TITLE
Update repo structure

### LINKED ISSUE #3: Setup core app
1. Refactor repo structure:
   1. create new folder "core" in root of the repo and move there all current folders in the root folder.
   2. set the moved folders as python module (hint: https://naucse.python.cz/course/mi-pyt/intro/distribution/)
2. Update "workdir" config in Dockerfile to created "core" folder to fetch correctly python code into the docker image.
3. Prepare python venv to enable to run the python code for anybody who faces the repo.

Hint: https://github.com/MeStrak/dr-sven/blob/main/pyproject.toml

### PR DESCRIPTION
**Pull request by Oleksandr6676**
Created core folder, moved py modules to created folder, created empty requirements.txt
Closes #3

### CODE REVIEW

**Comment by Oleksandr6676** [comment]
Hi Jan. Requirements.txt file is empty at the moment. We have more than 30 packages inside this repo. What packages we will be using inside our core app image? That's what I actually get  after pip freeze command. I'm pretty sure that we will be using at least requests :D
bleach==4.1.0
build==0.7.0
certifi==2021.10.8
charset-normalizer==2.0.9
colorama==0.4.4
docutils==0.18.1
idna==3.3
importlib-metadata==4.8.2
keyring==23.4.0
packaging==21.3
pep517==0.12.0
pkginfo==1.8.2
Pygments==2.10.0
pyparsing==3.0.6
pywin32-ctypes==0.2.0
readme-renderer==30.0
requests==2.26.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
six==1.16.0
tomli==1.2.2
tqdm==4.62.3
twine==3.7.1
urllib3==1.26.7
webencodings==0.5.1
zipp==3.6.0

**Comment by JanMate** [comment]
> Hi Jan. Requirements.txt file is empty at the moment. We have more than 30 packages inside this repo. What packages we will be using inside our core app image? That's what I actually get after pip freeze command. I'm pretty sure that we will be using at least requests and some others, but it's pretty hard to understand which one exactly
> 
> bleach==4.1.0 build==0.7.0 certifi==2021.10.8 charset-normalizer==2.0.9 colorama==0.4.4 docutils==0.18.1 idna==3.3 importlib-metadata==4.8.2 keyring==23.4.0 packaging==21.3 pep517==0.12.0 pkginfo==1.8.2 Pygments==2.10.0 pyparsing==3.0.6 pywin32-ctypes==0.2.0 readme-renderer==30.0 requests==2.26.0 requests-toolbelt==0.9.1 rfc3986==1.5.0 six==1.16.0 tomli==1.2.2 tqdm==4.62.3 twine==3.7.1 urllib3==1.26.7 webencodings==0.5.1 zipp==3.6.0

You are talking about 30 packages in the repo, but are they really part of the repo? Are they rather part of your python virtual env?

**Comment by JanMate** [comment]
Please, rename 'requirements.txt.txt' to 'requirements.txt'. Otherwise, I won't work in dockerfile properly.

**Review by JanMate — CHANGES_REQUESTED** [review]
Please, study Poetry and set all configuration files including 'pyproject.toml' file.

Hint: 
- https://python-poetry.org/docs/
- https://github.com/MeStrak/dr-sven/blob/main/pyproject.toml

**Review by JanMate — APPROVED** [review]
I set the pyproject.toml and CI pipeline to support semantic version.

**Pull request merged**
